# Generated by Django 3.2.6 on 2021-09-09 16:59
# Edited by Igorello74 on 2021-09-09 17:09

from django.db import migrations, models
from django.db.migrations.operations.fields import RemoveField


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0006_booktaking_is_returned'),
        ('readersRecords', '0002_reader_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='books'
        ),
        migrations.AddField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(db_table='bookTaking', to='booksRecords.BookInstance', blank=True),
        ),
    ]
