# Generated by Django 4.0.2 on 2022-06-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0007_delete_booktaking'),
        ('readersRecords', '0003_alter_reader_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(blank=True, db_table='bookTaking', to='booksRecords.BookInstance', verbose_name='книги'),
        ),
    ]
