# Generated by Django 4.0.2 on 2022-07-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersRecords', '0008_alter_reader_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='group',
            field=models.CharField(blank=True, help_text='номер и строчная литера класса без пробела, например: 10а', max_length=3, verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(help_text='например, Иванов Иван', max_length=100, verbose_name='фамилия, имя'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='profile',
            field=models.CharField(blank=True, help_text='например, ИТ, ТЕХ и т. п.', max_length=20, verbose_name='профиль'),
        ),
    ]
