# Generated by Django 4.0.2 on 2022-08-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersRecords', '0009_alter_reader_group_alter_reader_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='role',
            field=models.CharField(choices=[('TE', 'учитель'), ('ST', 'ученик'), ('OTH', 'иной')], default='ST', max_length=3, verbose_name='роль'),
        ),
    ]
