# Generated by Django 4.0.2 on 2022-08-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersRecords', '0010_alter_reader_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reader',
            name='readersReco_role_46b1c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='reader',
            name='readersReco_group_bc8b32_idx',
        ),
        migrations.AddIndex(
            model_name='reader',
            index=models.Index(fields=['role', 'group', 'name'], name='readersReco_role_27818a_idx'),
        ),
        migrations.AddIndex(
            model_name='reader',
            index=models.Index(fields=['group'], name='readersReco_group_858150_idx'),
        ),
    ]
