# Generated by Django 4.0.8 on 2023-05-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersRecords', '0011_remove_reader_readersreco_role_46b1c9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='notes',
            field=models.TextField(blank=True, verbose_name='заметки'),
        ),
    ]
