# Generated by Django 4.0.8 on 2023-06-07 14:05

from django.db import migrations
import readersRecords.models


class Migration(migrations.Migration):

    dependencies = [
        ('readersRecords', '0012_alter_reader_first_lang_alter_reader_second_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='first_lang',
            field=readersRecords.models.Reader.LangField(blank=True, max_length=20, verbose_name='Первый язык'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='group',
            field=readersRecords.models.Reader.GroupField(blank=True, help_text='номер и строчная литера класса без пробела, например: 10а', max_length=10, verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='second_lang',
            field=readersRecords.models.Reader.LangField(blank=True, max_length=20, verbose_name='Второй язык'),
        ),
    ]
