# Generated by Django 4.2.3 on 2023-07-03 22:24

from django.db import migrations, models
import readersRecords.models


class Migration(migrations.Migration):
    dependencies = [
        ("readersRecords", "0012_alter_reader_first_lang_alter_reader_second_lang"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reader",
            options={
                "ordering": ["role", "group_num", "group_letter", "name"],
                "verbose_name": "читатель",
                "verbose_name_plural": "читатели",
            },
        ),
        migrations.RemoveIndex(
            model_name="reader",
            name="readersReco_role_27818a_idx",
        ),
        migrations.RemoveIndex(
            model_name="reader",
            name="readersReco_group_858150_idx",
        ),
        migrations.RemoveField(
            model_name="reader",
            name="group",
        ),
        migrations.AddField(
            model_name="reader",
            name="group_letter",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="буква класса"
            ),
        ),
        migrations.AddField(
            model_name="reader",
            name="group_num",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="номер класса"
            ),
        ),
        migrations.AlterField(
            model_name="reader",
            name="first_lang",
            field=readersRecords.models.LangField(
                blank=True, max_length=20, verbose_name="Первый язык"
            ),
        ),
        migrations.AlterField(
            model_name="reader",
            name="second_lang",
            field=readersRecords.models.LangField(
                blank=True, max_length=20, verbose_name="Второй язык"
            ),
        ),
        migrations.AddIndex(
            model_name="reader",
            index=models.Index(
                fields=["role", "group_num", "group_letter", "name"],
                name="readersReco_role_120d2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reader",
            index=models.Index(
                fields=["group_num", "group_letter"],
                name="readersReco_group_n_bda6c3_idx",
            ),
        ),
    ]
