# Generated by Django 4.2.3 on 2023-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operationsLog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logrecord",
            options={
                "ordering": ["-datetime"],
                "verbose_name": "запись журнала",
                "verbose_name_plural": "записи журнала",
            },
        ),
        migrations.AddIndex(
            model_name="logrecord",
            index=models.Index(
                fields=["-datetime"], name="operationsL_datetim_ce392f_idx"
            ),
        ),
    ]
