# Generated by Django 4.2.3 on 2023-08-22 11:02

from django.db import migrations, models
import operationsLog.models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsLog', '0002_alter_logrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='backup_file',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, editable=False, path=operationsLog.models.get_backup_dir, verbose_name='резервная копия'),
        ),
    ]
