# Generated by Django 4.0.2 on 2022-08-24 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booksRecords', '0017_alter_bookinstance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='номер накладной', max_length=50, verbose_name='номер')),
                ('custom_number', models.PositiveSmallIntegerField(help_text='номер в книге суммарного учёта', verbose_name='учётный номер')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='дата')),
                ('vendor', models.CharField(blank=True, max_length=50, verbose_name='поставщик')),
                ('order_type', models.CharField(choices=[('M', 'основной'), ('A', 'дополнительный')], default='M', max_length=1, verbose_name='тип заказа')),
            ],
            options={
                'verbose_name': 'накладная',
                'verbose_name_plural': 'накладные',
            },
        ),
        migrations.CreateModel(
            name='BookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(blank=True, max_length=20, verbose_name='инвентарный номер')),
                ('num_bought', models.PositiveSmallIntegerField(verbose_name='количество купленных экзепляров')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена экземпляра')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksRecords.book', verbose_name='книга')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseRecords.bookinvoice', verbose_name='накладная')),
            ],
            options={
                'verbose_name': 'закупка книги',
                'verbose_name_plural': 'закупки книг',
            },
        ),
    ]
