# Generated by Django 4.0.2 on 2022-08-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseRecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinvoice',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='номер накладной'),
        ),
    ]
