# Generated by Django 4.0.2 on 2022-08-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseRecords', '0002_alter_bookinvoice_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInvoice',
            new_name='Invoice',
        ),
    ]
