# Generated by Django 4.0.2 on 2022-08-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0017_alter_bookinstance_options_and_more'),
        ('purchaseRecords', '0003_rename_bookinvoice_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpurchase',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='booksRecords.book', verbose_name='книга'),
        ),
    ]
