# Generated by Django 4.0.2 on 2022-08-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0017_alter_bookinstance_options_and_more'),
        ('purchaseRecords', '0005_alter_bookpurchase_price_alter_invoice_custom_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(blank=False, max_length=20, verbose_name='инвентарный номер')),
                ('num_bought', models.PositiveSmallIntegerField(verbose_name='количество купленных экзепляров')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена экземпляра, ₽')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='booksRecords.book', verbose_name='книга')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchaseRecords.invoice', verbose_name='накладная')),
            ],
            options={
                'verbose_name': 'инвентарная позиция',
                'verbose_name_plural': 'инвентарные позиции',
            },
        ),
        migrations.DeleteModel(
            name='BookPurchase',
        ),
    ]
