# Generated by Django 4.0.2 on 2022-08-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseRecords', '0006_inventoryitem_delete_bookpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='num_bought',
            field=models.PositiveSmallIntegerField(verbose_name='количество купленных экземпляров'),
        ),
    ]
