# Generated by Django 3.2.6 on 2021-08-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name'], name='booksRecord_name_a67210_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['authors'], name='booksRecord_authors_b118b5_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='booksRecord_isbn_69e843_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['inventory_number'], name='booksRecord_invento_0d5437_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['grade', 'subject'], name='booksRecord_grade_81461b_idx'),
        ),
    ]
