# Generated by Django 3.2.6 on 2021-08-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0002_auto_20210826_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('barcode', models.CharField(help_text='идентификатор книги, уникальный для каждого экземпляра; совпадает с номером штрихкода на наклейке', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Штрихкод')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'в хранилище'), (1, 'на руках'), (2, 'истёк срок возврата'), (3, 'снята с учёта')], default=0, editable=False, verbose_name='статус')),
                ('book', models.ForeignKey(help_text='ссылка на модель Книга :Model:`booksRecord.Book`', on_delete=django.db.models.deletion.CASCADE, to='booksRecords.book', verbose_name='книга')),
            ],
            options={
                'verbose_name': 'экземпляр книги',
                'verbose_name_plural': 'экземпляры книг',
                'ordering': ['barcode'],
            },
        ),
        migrations.AddIndex(
            model_name='bookinstance',
            index=models.Index(fields=['status'], name='booksRecord_status_1594e5_idx'),
        ),
    ]
