# Generated by Django 3.2.6 on 2021-09-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readersRecords', '0001_initial'),
        ('booksRecords', '0004_auto_20210826_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_taken', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время взятия книги')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='bookinstance',
            name='booksRecord_taken_b_a3710a_idx',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='taken_by',
        ),
        migrations.AddField(
            model_name='booktaking',
            name='book_instance',
            field=models.ForeignKey(limit_choices_to={'status': 0}, on_delete=django.db.models.deletion.CASCADE, to='booksRecords.bookinstance'),
        ),
        migrations.AddField(
            model_name='booktaking',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readersRecords.reader', verbose_name='читатель'),
        ),
    ]
