# Generated by Django 3.2.6 on 2021-09-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0005_auto_20210905_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktaking',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='возвращена?'),
        ),
    ]
