# Generated by Django 4.0.2 on 2022-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0007_delete_booktaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, verbose_name='заметки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='city',
            field=models.CharField(blank=True, help_text='город издания книги, без "г. "', max_length=30, verbose_name='город издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='номер издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=20, verbose_name='издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='год издания'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='barcode',
            field=models.CharField(help_text='идентификатор книги, уникальный для каждого экземпляра; совпадает с номером штрихкода на наклейке', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Штрихкод'),
        ),
    ]
