# Generated by Django 4.0.2 on 2022-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0008_book_notes_alter_book_city_alter_book_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(blank=True, help_text='Например: "математика", "русский язык", "математика углублённая"', max_length=100, verbose_name='предмет'),
        ),
    ]
