# Generated by Django 4.0.2 on 2022-07-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0011_alter_book_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
    ]
