# Generated by Django 4.0.2 on 2022-07-12 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0012_alter_subject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booksRecords.subject', verbose_name='предмет'),
        ),
    ]
