# Generated by Django 4.0.2 on 2022-08-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0014_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='booksRecord_isbn_69e843_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='booksRecord_invento_0d5437_idx',
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['subject'], name='booksRecord_subject_0a11ee_idx'),
        ),
    ]
