# Generated by Django 4.0.2 on 2022-08-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0015_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='represents_multiple',
            field=models.BooleanField(choices=[(False, 'индивидуальный'), (True, 'множественный')], default=False, verbose_name='Вид экземпляра'),
        ),
    ]
