# Generated by Django 4.0.2 on 2022-08-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksRecords', '0016_bookinstance_represents_multiple'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'verbose_name': 'экземпляр книги', 'verbose_name_plural': 'экземпляры книг'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='inventory_number',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Желательно придерживаться какого-то единообразия.\n        Например: вместо ̶ф̶р̶а̶н̶ц̶у̶з̶с̶к̶и̶й̶ ̶я̶з̶ы̶к̶ ̶в̶т̶о̶р̶о̶й — второй французский\n        язык. Или: вместо ̶м̶а̶т̶е̶м̶а̶т̶и̶к̶а̶ у̶г̶л̶у̶б̶л̶ё̶н̶н̶а̶я —\n        углублённая математика', max_length=100, unique=True, verbose_name='название'),
        ),
    ]
