# Generated by Django 4.2.3 on 2023-08-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksRecords", "0017_alter_bookinstance_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinstance",
            old_name="barcode",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="id",
            field=models.CharField(
                help_text="идентификатор книги, уникальный для каждого экземпляра; совпадает с номером штрихкода на наклейке",
                max_length=30,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="код",
            ),
        ),
    ]
